---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
  annotations:
    eck.k8s.elastic.co/license: basic
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  version: {{ required "A Kibana version is required" .Values.version }}
  {{- with .Values.image }}
  image: {{ . }}
  {{- end }}
  {{- with .Values.count }}
  count: {{ . }}
  {{- end }}
  elasticsearchRef: {{ required "An elasticsearchRef is required" .Values.elasticsearchRef }}
  {{- with .Values.enterpriseSearchRef }}
  enterpriseSearchRef: {{ . }}
  {{- end }}
  {{- with .Values.config }}
  config: {{ . }}
  {{- end }}
  {{- with .Values.http }}
  http: {{ . }}
  {{- end }}
  {{- with .Values.podTemplate }}
  podTemplate: {{ . }}
  {{- end }}
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.secureSettings }}
  secureSettings: {{ . }}
  {{- end }}
  {{- with .Values.serviceAccountName }}
  serviceAccountName: {{ . }}
  {{- end }}
  {{- with .Values.monitoring }}
  monitoring: {{ . }}
  {{- end }}
