apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: cluster1
  namespace: ns1
spec:
  version: 8.15.0
  remoteClusters:
    - name: first-rc
      elasticsearchRef:
        name: cluster2
        namespace: ns2
      apiKey:
        access:
          search:
            names:
              - kibana_sample_data_ecommerce
              - bla
#    - name: rc-to-cluster3
#      elasticsearchRef:
#        name: cluster3
#        namespace: ns3
#      apiKey:
#        access:
#          search:
#            names:
#              - kibana_sample_data_ecommerce
  nodeSets:
    - name: default
      config:
        node.store.allow_mmap: false
        ##remote_cluster_server.enabled: true
      count: 3
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: ns1
spec:
  http:
    service:
      spec:
        # expose this cluster Service with a LoadBalancer
        type: LoadBalancer
  version: 8.15.0
  count: 1
  elasticsearchRef:
    name: "cluster1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns2
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: cluster2
  namespace: ns2
spec:
  version: 8.15.0
  remoteClusterServer:
    enabled: true
  nodeSets:
    - name: default
      config:
        node.store.allow_mmap: false
        remote_cluster_server.enabled: true
      count: 3
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: ns2
spec:
  http:
    service:
      spec:
        # expose this cluster Service with a LoadBalancer
        type: LoadBalancer
  version: 8.15.0
  count: 1
  elasticsearchRef:
    name: "cluster2"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns3
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: cluster3
  namespace: ns3
spec:
  version: 8.15.0
  remoteClusterServer:
    enabled: true
  nodeSets:
    - name: default
      config:
        node.store.allow_mmap: false
        remote_cluster_server.enabled: true
      count: 1
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: ns3
spec:
  http:
    service:
      spec:
        # expose this cluster Service with a LoadBalancer
        type: LoadBalancer
  version: 8.15.0
  count: 1
  elasticsearchRef:
    name: "cluster3"